name: Copy & Build on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH private key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Copy all repo files to EC2
      run: |
        scp -i key.pem -r * ubuntu@YOUR_EC2_IP:/var/www/html/sales/

    - name: SSH into EC2 & build + start
      run: |
        ssh -i key.pem ubuntu@YOUR_EC2_IP << 'EOF'
          cd /var/www/html/sales
          npm install
          npm run build
          pm2 restart all || pm2 start npm --name sales-dashboard -- start
        EOF
